### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by fullsalvo** [fullsalvo/wz-utils#3]
- Autowzb
  - [ ] Allow for template generation
  - [ ] Sort colors
- Reload-desktop
  - [x] Add font change controls
    - [x] Make font change optional (Currently change function script variable)
  - [ ] Expand this to more wms/programs
    - [ ] Terminals
      - [x] URxvt/Rxvt/XTerm
      - [x] Termite
      - [ ] Terminator/Gnome-Terminal
      - [ ] st + [xst](https://github.com/neeasade/xst)
    - [ ] Window Managers
      - [x] i3
      - [ ] bspwm
      - [x] Openbox
      - [x] Awesome
      - [x] herbstluftwm
      - [ ] etc
- WZGrab
  - [ ] Allow for optional additions to templates
  - [ ] Add a utility to automatically switch to the new scheme
